(** Saga-instance identifier carried in every cross-BC integration
    event that participates in a Process Manager workflow.

    Generated by the saga initiator (e.g. PM's reconciler when emitting
    [Trade_intents_planned_integration_event]) and echoed verbatim by
    every downstream BC handler. The Process Manager runtime at
    [shared/lib/workflow_engine] uses the correlation id as the lookup
    key into its instance store — see
    [Workflow_engine.WORKFLOW.correlation_of_event].

    Opaque to enforce the non-empty invariant; the underlying
    representation is a UUID v4 string but callers must not depend on
    that. *)

type t = private string

val of_string : string -> t
(** Smart constructor. Raises [Invalid_argument] on an empty string;
    other strings are accepted verbatim (for ids minted outside this
    process — bus messages from another node, replays from a log). *)

val generate : unit -> t
(** Fresh UUIDv4. Suitable as a saga-key minted at the boundary of a
    BC that initiates a Process Manager instance. *)

val to_string : t -> string

val equal : t -> t -> bool
val compare : t -> t -> int
val hash : t -> int
