(** Inbound command to the Broker BC: "submit this order to the
    upstream broker."

    Wire-format DTO — primitives + view-model DTOs, no
    {!Core.Instrument.t} / {!Core.Side.t} / {!Core.Decimal.t}.
    Compile-time guarantee via [@@deriving yojson]: the message
    that travels on the InMemory bus today serialises as-is on a
    real (network) bus tomorrow.

    [client_order_id] is the broker-wire identity AND the
    cross-BC saga key. Generated by the caller (HTTP composition
    root) via {!Broker.generate_client_order_id} so the format
    matches the active broker's wire validator (BCS dashed-UUID,
    Finam letters/digits/space). The same string flows through
    every {!Order_event.t} variant emitted by the handler. *)

type t = {
  client_order_id : string;
  symbol : string;
      (** Qualified instrument: [TICKER@MIC[/BOARD]] —
        {!Core.Instrument.of_qualified} round-trips it. *)
  side : string;  (** ["BUY"] | ["SELL"]. *)
  quantity : float;
  kind : Queries.Order_kind_view_model.t;
  tif : string;  (** ["GTC"] | ["DAY"] | ["IOC"] | ["FOK"]. *)
}
[@@deriving yojson]
